### ISSUE TITLE
Apache segmentation faults after update

### ISSUE THREAD

**Issue by fbhdk** [vgno/mod_vgremoteip#2]
mod_vgremoteip makes Apache segfault after the OS has been updated: 

OS: CentOS 6, latest patches

Apache tested with both httpd package from yum and newest apache 2.2, custom compiled. 

What I see is: 
[Tue Jun 16 13:36:27 2015] [notice] child pid 23157 exit signal Segmentation fault (11)
[Tue Jun 16 13:36:28 2015] [notice] child pid 23221 exit signal Segmentation fault (11)
[Tue Jun 16 13:36:34 2015] [notice] child pid 23227 exit signal Segmentation fault (11)
[Tue Jun 16 13:36:36 2015] [notice] child pid 23182 exit signal Bus error (7)

This is a stack trace created with GDB when attaching to apache: 

Program received signal SIGPIPE, Broken pipe.
0x00007f4c64dde9ab in writev () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f4c64dde9ab in writev () from /lib64/libc.so.6
#1  0x00007f4c652cba3e in apr_socket_sendv () from /usr/lib64/libapr-1.so.0
#2  0x00007f4c667ed253 in ?? ()
#3  0x00007f4c667ee205 in ap_core_output_filter ()
#4  0x00007f4c667fe99b in ap_http_header_filter ()
#5  0x00007f4c667e31a0 in ap_content_length_filter ()
#6  0x00007f4c66800766 in ap_byterange_filter ()
#7  0x00007f4c5fbb9d81 in ?? () from /etc/httpd/modules/mod_deflate.so
#8  0x00007f4c667e7ddc in ?? ()
#9  0x00007f4c667eecd0 in ap_run_handler ()
#10 0x00007f4c667f258e in ap_invoke_handler ()
#11 0x00007f4c667fdc50 in ap_process_request ()
#12 0x00007f4c667faac8 in ?? ()
#13 0x00007f4c667f67d8 in ap_run_process_connection ()
#14 0x00007f4c66802ad7 in ?? ()
#15 0x00007f4c66802da6 in ?? ()
#16 0x00007f4c668033f3 in ap_mpm_run ()
#17 0x00007f4c667da9b0 in main ()

(gdb) bt full
#0  0x00007f4c64dde9ab in writev () from /lib64/libc.so.6

No symbol table info available.
#1  0x00007f4c652cba3e in apr_socket_sendv () from /usr/lib64/libapr-1.so.0

No symbol table info available.
#2  0x00007f4c667ed253 in ?? ()

No symbol table info available.
#3  0x00007f4c667ee205 in ap_core_output_filter ()

No symbol table info available.
#4  0x00007f4c667fe99b in ap_http_header_filter ()

No symbol table info available.
#5  0x00007f4c667e31a0 in ap_content_length_filter ()

No symbol table info available.
#6  0x00007f4c66800766 in ap_byterange_filter ()

No symbol table info available.
#7  0x00007f4c5fbb9d81 in ?? () from /etc/httpd/modules/mod_deflate.so

No symbol table info available.
#8  0x00007f4c667e7ddc in ?? ()

No symbol table info available.
#9  0x00007f4c667eecd0 in ap_run_handler ()

No symbol table info available.
#10 0x00007f4c667f258e in ap_invoke_handler ()

No symbol table info available.
#11 0x00007f4c667fdc50 in ap_process_request ()

No symbol table info available.
#12 0x00007f4c667faac8 in ?? ()

No symbol table info available.
#13 0x00007f4c667f67d8 in ap_run_process_connection ()

No symbol table info available.
#14 0x00007f4c66802ad7 in ?? ()

No symbol table info available.
#15 0x00007f4c66802da6 in ?? ()

No symbol table info available.
#16 0x00007f4c668033f3 in ap_mpm_run ()

No symbol table info available.
#17 0x00007f4c667da9b0 in main ()

No symbol table info available.

I am not sure if there is any more information I can provide or anything else I can do to help?

**Comment by olesku** [comment]
Hello,

Im not able to reproduce on CentOS 6.6 with latest patches (Apache 2.2.15).
Is there any possibility you could do a debuginfo-install httpd, activate coredumps and send me the coredump file ?
